import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/components/theme-provider"
import { ModeToggle } from "@/components/modetoggle" 
import Header from "@/components/header";
import Footer from "@/components/footer";
import { inter } from "@/utils/font";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono", 
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${inter.variable} antialiased`}
      >
        <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
            <div className="grid h-[100dvh] grid-rows-[auto_1fr_auto]">
              <Header/>
              <main className="pt-1">
              {children}
              </main>
              <Footer/>
            </div>

            <div className="absolute bottom-5 right-5" >
              <ModeToggle/>
            </div>
          </ThemeProvider>
        
      </body>
    </html>
  );
}
